### ISSUE TITLE
[WSL2] Incomplete repository after create?

### ISSUE THREAD

**Issue by Bandit** [agneym/svelte-tailwind-snowpack#2]
`npx create-snowpack-app testapp --template @snowpack/app-template-svelte`

It gets up to this point:

```
- Initializing git repo.
- Could not complete.

Quickstart:

  cd testapp
  npm start

All Commands:

  npm install      Install your dependencies. (We already ran this one for you!)
  npm start        Start your development server.
  npm run build    Build your website for production.
  npm test         Run your tests.
```

Looking at the directory, there's no `svelte.config.js` or `tailwind.config.js`? Also running `npm start` seems to work, but changes to the files don't trigger a rebuild or browser refresh.

**Comment by agneym** [comment]
Bad documentation. Fixed now. Can you confirm this? 

```
npx create-snowpack-app dir-name --template svelte-tailwind-snowpack
```

Thanks for reporting.
