### ISSUE TITLE
Jest hangs on this repo

### ISSUE THREAD

**Issue by negcx** [agneym/svelte-tailwind-snowpack#3]
Thanks for creating this starter.

Jest hangs with svelte-preprocess - know of any solution there?

**Comment by agneym** [comment]
Originally an issue of pikapkg/snowpack#703

Noting here for tracking.

**Comment by agneym** [comment]
Moved to using `chai` and `@web/test-runner` as in the official snowpack repository. 

https://github.com/agneym/svelte-tailwind-snowpack/commit/f91b4ce56a29f0170b0b5507ed1236ad6823f4ef
