### ISSUE TITLE
Why is the bare bundle 36 KBs ?

### ISSUE THREAD

**Issue by tayelno** [agneym/svelte-tailwind-snowpack#4]
### Issue

The bundled file size is `36 KB` without adding anything to the code, apparently it imports the `svelte/internal.js` whole to the bundle, which I think should not be the case, as if you use the normal svelte template [here](https://github.com/sveltejs/template) the bundle size is `1.3 KB`

### Steps to reproduce issue

```sh
npx create-snowpack-app app--template svelte-tailwind-snowpack

cd app

npm i -D @snowpack/plugin-webpack
```

add plugin to `snowpack.config.json`

```json
{
  "extends": "@snowpack/app-scripts-svelte",
   "scripts": {},
   "plugins": ["@snowpack/plugin-webpack"]
}
```

```sh
npm run build

  ./build Building your application...

  mount:public............[DONE] mount public --to /
  mount:src...............[DONE] mount src --to /_dist_
  build:.js,.jsx,.ts,.tsx.[DONE] (default) esbuild
  build:svelte............[DONE] (plugin) @snowpack/plugin-svelte
  bundle:*................[DONE] (plugin) @snowpack/plugin-webpack

▼ Console

  [log] ! optimizing dependencies...
  [log]
    ⦿ web_modules/           size       gzip       brotli
      └─ svelte/internal.js  51.68 KB   13.04 KB   11.28 KB


  [log]                              Asset      Size  Chunks                         Chunk Names
                 __snowpack__/env.js  56 bytes          [emitted]
  css/index.9d8e1494ee88da277ad0.css  6.74 KiB       0  [emitted] [immutable]  index
                         favicon.ico  1.12 KiB          [emitted]
    js/index.73420404e48087adf0d8.js  35.9 KiB       0  [emitted] [immutable]  index
                            logo.svg  1.12 KiB          [emitted]
                          robots.txt  67 bytes          [emitted]

▶ Build Complete!

```

I am just wondering if there is a way to configure it to treeshake unused code from svelte, as that is one of the main reasons we are using svelte

**Comment by agneym** [comment]
Hey @tayelno 👋 Thanks for reporting. 

Unfortunately this is an issue with the official plugin that snowpack uses for Svelte, available on [official repository](https://github.com/pikapkg/snowpack/tree/master/packages/%40snowpack/app-scripts-svelte).

**Comment by tayelno** [comment]
Just a note about this, but since this is the case, omitting a snowpack `bundle:*` script will result in a much better performance for browsers that can use `<script module>` but with a bigger overall download size for the user.
