### ISSUE TITLE
npx create failed to install husky

### ISSUE THREAD

**Issue by ahmetkca** [agneym/svelte-tailwind-snowpack#9]
so i used `npx create-snowpack-app chat-app-with-svelte --template svelte-tailwind-snowpack` and it says  - Success! but it failed to install husky.

**Comment by agneym** [comment]
Currently `create-snowpack-app` installs dependencies first and initializes git repository in the next step. This is why installing husky git hooks are failing.  

My hands are tied on the template unless the order of these steps change. Sorry
